/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ctrl_7 (
    input clk,
    input rst,
    output reg [3:0] regfile_write_address,
    output reg [3:0] regfile_read_address_a,
    output reg [3:0] regfile_read_address_b,
    output reg we_regfile,
    output reg [15:0] literal,
    output reg [5:0] alufn,
    input z,
    output reg bsel,
    output reg outsel
  );
  
  
  
  localparam ADD = 6'h00;
  
  localparam SUB = 6'h01;
  
  localparam MUL = 6'h02;
  
  localparam AND = 6'h18;
  
  localparam OR = 6'h1e;
  
  localparam XOR = 6'h16;
  
  localparam A = 6'h1a;
  
  localparam B = 6'h1c;
  
  localparam BCA = 6'h12;
  
  localparam ACB = 6'h14;
  
  localparam SHL = 6'h20;
  
  localparam SHR = 6'h21;
  
  localparam SRA = 6'h23;
  
  localparam ROL = 6'h24;
  
  localparam ROR = 6'h25;
  
  localparam RVA = 6'h27;
  
  localparam CMPEQ = 6'h33;
  
  localparam CMPLT = 6'h35;
  
  localparam CMPLE = 6'h37;
  
  localparam REG_P1 = 4'h0;
  
  localparam REG_P2 = 4'h1;
  
  localparam REG_ROUND = 4'h2;
  
  localparam REG_LEDCD = 4'h3;
  
  localparam REG_TEMP = 4'h4;
  
  localparam REG_TEMP2 = 4'h5;
  
  localparam REG_TEMP3 = 4'h6;
  
  localparam REG_TEMP4 = 4'h7;
  
  localparam REG_7SEG = 4'h8;
  
  localparam REG_P1LED = 4'h9;
  
  localparam REG_P2LED = 4'ha;
  
  localparam REG_LED = 4'hb;
  
  localparam REG_RND = 4'hc;
  
  localparam REG_TIMER = 4'hd;
  
  localparam REG_SW = 4'he;
  
  localparam START_game_fsm = 6'd0;
  localparam S1_game_fsm = 6'd1;
  localparam S2_game_fsm = 6'd2;
  localparam S3_game_fsm = 6'd3;
  localparam S4_game_fsm = 6'd4;
  localparam S5_game_fsm = 6'd5;
  localparam L1_game_fsm = 6'd6;
  localparam L2_game_fsm = 6'd7;
  localparam L3_game_fsm = 6'd8;
  localparam L4_game_fsm = 6'd9;
  localparam R1_game_fsm = 6'd10;
  localparam R2_game_fsm = 6'd11;
  localparam R3_game_fsm = 6'd12;
  localparam R4_game_fsm = 6'd13;
  localparam R5_game_fsm = 6'd14;
  localparam R6_game_fsm = 6'd15;
  localparam R7_game_fsm = 6'd16;
  localparam R8_game_fsm = 6'd17;
  localparam R9_game_fsm = 6'd18;
  localparam R10_game_fsm = 6'd19;
  localparam F1_game_fsm = 6'd20;
  localparam F2_game_fsm = 6'd21;
  localparam F3_game_fsm = 6'd22;
  localparam F4_game_fsm = 6'd23;
  localparam F5_game_fsm = 6'd24;
  localparam F6_game_fsm = 6'd25;
  localparam F7_game_fsm = 6'd26;
  localparam F8_game_fsm = 6'd27;
  localparam F9_game_fsm = 6'd28;
  localparam C1_game_fsm = 6'd29;
  localparam C2_game_fsm = 6'd30;
  localparam C3_game_fsm = 6'd31;
  localparam C4_game_fsm = 6'd32;
  localparam C5_game_fsm = 6'd33;
  localparam C6_game_fsm = 6'd34;
  localparam C7_game_fsm = 6'd35;
  localparam C8_game_fsm = 6'd36;
  localparam C9_game_fsm = 6'd37;
  localparam C10_game_fsm = 6'd38;
  localparam C11_game_fsm = 6'd39;
  localparam C12_game_fsm = 6'd40;
  localparam C13_game_fsm = 6'd41;
  localparam C14_game_fsm = 6'd42;
  localparam C15_game_fsm = 6'd43;
  localparam C16_game_fsm = 6'd44;
  localparam C17_game_fsm = 6'd45;
  localparam C18_game_fsm = 6'd46;
  localparam C19_game_fsm = 6'd47;
  localparam C20_game_fsm = 6'd48;
  localparam C21_game_fsm = 6'd49;
  localparam P1W1_game_fsm = 6'd50;
  localparam P1W2_game_fsm = 6'd51;
  localparam P1W3_game_fsm = 6'd52;
  localparam P2W1_game_fsm = 6'd53;
  localparam P2W2_game_fsm = 6'd54;
  localparam P2W3_game_fsm = 6'd55;
  localparam W1_game_fsm = 6'd56;
  localparam W2_game_fsm = 6'd57;
  localparam W3_game_fsm = 6'd58;
  localparam E1_game_fsm = 6'd59;
  localparam E2_game_fsm = 6'd60;
  localparam E3_game_fsm = 6'd61;
  localparam E4_game_fsm = 6'd62;
  
  reg [5:0] M_game_fsm_d, M_game_fsm_q = START_game_fsm;
  
  always @* begin
    M_game_fsm_d = M_game_fsm_q;
    
    we_regfile = 1'h0;
    regfile_write_address = 4'h4;
    regfile_read_address_a = 4'h4;
    regfile_read_address_b = 4'hd;
    literal = 1'h0;
    bsel = 1'h0;
    outsel = 1'h0;
    alufn = 6'h1c;
    if (rst) begin
      M_game_fsm_d = START_game_fsm;
    end else begin
      
      case (M_game_fsm_q)
        START_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'he;
          literal = 16'h0040;
          bsel = 1'h1;
          alufn = 6'h18;
          if (~z) begin
            M_game_fsm_d = S1_game_fsm;
          end
        end
        S1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h0;
          literal = 1'h0;
          bsel = 1'h1;
          M_game_fsm_d = S2_game_fsm;
        end
        S2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h1;
          literal = 1'h0;
          bsel = 1'h1;
          M_game_fsm_d = S3_game_fsm;
        end
        S3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h2;
          literal = 3'h5;
          bsel = 1'h1;
          M_game_fsm_d = S4_game_fsm;
        end
        S4_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'h0;
          regfile_write_address = 4'h9;
          M_game_fsm_d = S5_game_fsm;
        end
        S5_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'h1;
          regfile_write_address = 4'ha;
          M_game_fsm_d = L1_game_fsm;
        end
        L1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'hb;
          literal = 1'h0;
          bsel = 1'h1;
          M_game_fsm_d = L2_game_fsm;
        end
        L2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'hc;
          regfile_write_address = 4'h4;
          literal = 2'h3;
          bsel = 1'h1;
          alufn = 6'h21;
          M_game_fsm_d = L3_game_fsm;
        end
        L3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_write_address = 4'h4;
          literal = 3'h6;
          bsel = 1'h1;
          alufn = 6'h02;
          M_game_fsm_d = L4_game_fsm;
        end
        L4_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_write_address = 4'h3;
          literal = 4'hd;
          bsel = 1'h1;
          alufn = 6'h21;
          M_game_fsm_d = R1_game_fsm;
        end
        R1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'hd;
          literal = 12'h8f2;
          bsel = 1'h1;
          M_game_fsm_d = R2_game_fsm;
        end
        R2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'h2;
          regfile_write_address = 4'h8;
          outsel = 1'h1;
          M_game_fsm_d = R3_game_fsm;
        end
        R3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h4;
          literal = 2'h3;
          bsel = 1'h1;
          M_game_fsm_d = R4_game_fsm;
        end
        R4_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_b = 4'hd;
          if (z) begin
            M_game_fsm_d = R5_game_fsm;
          end
        end
        R5_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h8;
          literal = 1'h0;
          bsel = 1'h1;
          M_game_fsm_d = R6_game_fsm;
        end
        R6_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'hd;
          literal = 9'h134;
          bsel = 1'h1;
          M_game_fsm_d = R7_game_fsm;
        end
        R7_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_b = 4'hd;
          if (z) begin
            M_game_fsm_d = R8_game_fsm;
          end
        end
        R8_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'h2;
          regfile_write_address = 4'h8;
          outsel = 1'h1;
          M_game_fsm_d = R9_game_fsm;
        end
        R9_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_write_address = 4'h4;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h01;
          if (z) begin
            M_game_fsm_d = F1_game_fsm;
          end else begin
            M_game_fsm_d = R10_game_fsm;
          end
        end
        R10_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'hd;
          literal = 10'h2fb;
          bsel = 1'h1;
          M_game_fsm_d = R4_game_fsm;
        end
        F1_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h3;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h18;
          if (z) begin
            M_game_fsm_d = F2_game_fsm;
          end else begin
            M_game_fsm_d = F3_game_fsm;
          end
        end
        F2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h4;
          literal = 5'h10;
          bsel = 1'h1;
          M_game_fsm_d = F4_game_fsm;
        end
        F3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h4;
          literal = 4'h8;
          bsel = 1'h1;
          M_game_fsm_d = F4_game_fsm;
        end
        F4_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h3;
          literal = 3'h6;
          bsel = 1'h1;
          alufn = 6'h18;
          if (z) begin
            M_game_fsm_d = F5_game_fsm;
          end else begin
            M_game_fsm_d = F6_game_fsm;
          end
        end
        F5_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_read_address_b = 4'he;
          regfile_write_address = 4'hb;
          literal = 3'h4;
          bsel = 1'h1;
          alufn = 6'h1e;
          M_game_fsm_d = F9_game_fsm;
        end
        F6_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h3;
          literal = 2'h2;
          bsel = 1'h1;
          alufn = 6'h18;
          if (z) begin
            M_game_fsm_d = F8_game_fsm;
          end else begin
            M_game_fsm_d = F7_game_fsm;
          end
        end
        F7_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_read_address_b = 4'he;
          regfile_write_address = 4'hb;
          literal = 2'h2;
          bsel = 1'h1;
          alufn = 6'h1e;
          M_game_fsm_d = F9_game_fsm;
        end
        F8_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_read_address_b = 4'he;
          regfile_write_address = 4'hb;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h1e;
          M_game_fsm_d = F9_game_fsm;
        end
        F9_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'he;
          regfile_write_address = 4'h4;
          literal = 16'h003f;
          bsel = 1'h1;
          alufn = 6'h18;
          if (~z) begin
            M_game_fsm_d = C1_game_fsm;
          end
        end
        C1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_write_address = 4'h5;
          literal = 3'h7;
          bsel = 1'h1;
          alufn = 6'h18;
          M_game_fsm_d = C2_game_fsm;
        end
        C2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h6;
          literal = 16'h00e8;
          bsel = 1'h1;
          M_game_fsm_d = C3_game_fsm;
        end
        C3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h6;
          regfile_read_address_b = 4'h5;
          regfile_write_address = 4'h7;
          alufn = 6'h21;
          M_game_fsm_d = C4_game_fsm;
        end
        C4_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h7;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h18;
          if (~z) begin
            M_game_fsm_d = P1W1_game_fsm;
          end else begin
            M_game_fsm_d = C5_game_fsm;
          end
        end
        C5_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h4;
          regfile_write_address = 4'h4;
          literal = 2'h3;
          bsel = 1'h1;
          alufn = 6'h21;
          M_game_fsm_d = C6_game_fsm;
        end
        C6_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h6;
          regfile_read_address_b = 4'h4;
          regfile_write_address = 4'h7;
          alufn = 6'h21;
          M_game_fsm_d = C7_game_fsm;
        end
        C7_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h7;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h18;
          if (~z) begin
            M_game_fsm_d = P2W1_game_fsm;
          end else begin
            M_game_fsm_d = C8_game_fsm;
          end
        end
        C8_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h6;
          literal = 16'h079e;
          bsel = 1'h1;
          M_game_fsm_d = C9_game_fsm;
        end
        C9_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h6;
          regfile_read_address_b = 4'h3;
          regfile_write_address = 4'h6;
          alufn = 6'h21;
          M_game_fsm_d = C10_game_fsm;
        end
        C10_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h6;
          regfile_read_address_b = 4'h3;
          regfile_write_address = 4'h6;
          alufn = 6'h21;
          M_game_fsm_d = C11_game_fsm;
        end
        C11_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h6;
          regfile_write_address = 4'h6;
          literal = 2'h3;
          bsel = 1'h1;
          alufn = 6'h18;
          M_game_fsm_d = C12_game_fsm;
        end
        C12_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h7;
          literal = 16'h0324;
          bsel = 1'h1;
          M_game_fsm_d = C13_game_fsm;
        end
        C13_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h5;
          literal = 3'h7;
          bsel = 1'h1;
          alufn = 6'h18;
          if (z) begin
            M_game_fsm_d = C14_game_fsm;
          end else begin
            M_game_fsm_d = C18_game_fsm;
          end
        end
        C14_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h7;
          regfile_read_address_b = 4'h4;
          regfile_write_address = 4'h7;
          alufn = 6'h21;
          M_game_fsm_d = C15_game_fsm;
        end
        C15_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h7;
          regfile_read_address_b = 4'h4;
          regfile_write_address = 4'h7;
          alufn = 6'h21;
          M_game_fsm_d = C16_game_fsm;
        end
        C16_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h7;
          regfile_write_address = 4'h7;
          literal = 2'h3;
          bsel = 1'h1;
          alufn = 6'h18;
          M_game_fsm_d = C17_game_fsm;
        end
        C17_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h7;
          regfile_read_address_b = 4'h6;
          alufn = 6'h33;
          if (~z) begin
            M_game_fsm_d = P1W1_game_fsm;
          end else begin
            M_game_fsm_d = P2W1_game_fsm;
          end
        end
        C18_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h7;
          regfile_read_address_b = 4'h5;
          regfile_write_address = 4'h7;
          alufn = 6'h21;
          M_game_fsm_d = C19_game_fsm;
        end
        C19_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h7;
          regfile_read_address_b = 4'h5;
          regfile_write_address = 4'h7;
          alufn = 6'h21;
          M_game_fsm_d = C20_game_fsm;
        end
        C20_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h7;
          regfile_write_address = 4'h7;
          literal = 2'h3;
          bsel = 1'h1;
          alufn = 6'h18;
          M_game_fsm_d = C21_game_fsm;
        end
        C21_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h7;
          regfile_read_address_b = 4'h6;
          alufn = 6'h33;
          if (~z) begin
            M_game_fsm_d = P2W1_game_fsm;
          end else begin
            M_game_fsm_d = P1W1_game_fsm;
          end
        end
        P1W1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h0;
          regfile_write_address = 4'h0;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h20;
          M_game_fsm_d = P1W2_game_fsm;
        end
        P1W2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h0;
          regfile_write_address = 4'h0;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h00;
          M_game_fsm_d = P1W3_game_fsm;
        end
        P1W3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'h0;
          regfile_write_address = 4'h9;
          M_game_fsm_d = W1_game_fsm;
        end
        P2W1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h1;
          regfile_write_address = 4'h1;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h20;
          M_game_fsm_d = P2W2_game_fsm;
        end
        P2W2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h1;
          regfile_write_address = 4'h1;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h00;
          M_game_fsm_d = P2W3_game_fsm;
        end
        P2W3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'h1;
          regfile_write_address = 4'ha;
          M_game_fsm_d = W1_game_fsm;
        end
        W1_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_a = 4'h2;
          regfile_write_address = 4'h2;
          literal = 1'h1;
          bsel = 1'h1;
          alufn = 6'h01;
          if (z) begin
            M_game_fsm_d = E1_game_fsm;
          end else begin
            M_game_fsm_d = W2_game_fsm;
          end
        end
        W2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'hd;
          literal = 12'h8f2;
          bsel = 1'h1;
          M_game_fsm_d = W3_game_fsm;
        end
        W3_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_b = 4'hd;
          if (z) begin
            M_game_fsm_d = L1_game_fsm;
          end
        end
        E1_game_fsm: begin
          we_regfile = 1'h0;
          regfile_read_address_a = 4'h0;
          regfile_read_address_b = 4'h1;
          alufn = 6'h35;
          if (z) begin
            M_game_fsm_d = E2_game_fsm;
          end else begin
            M_game_fsm_d = E3_game_fsm;
          end
        end
        E2_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'ha;
          literal = 1'h0;
          bsel = 1'h1;
          M_game_fsm_d = E4_game_fsm;
        end
        E3_game_fsm: begin
          we_regfile = 1'h1;
          regfile_write_address = 4'h9;
          literal = 1'h0;
          bsel = 1'h1;
          M_game_fsm_d = E4_game_fsm;
        end
        E4_game_fsm: begin
          we_regfile = 1'h1;
          regfile_read_address_b = 4'he;
          regfile_write_address = 4'h8;
          literal = 7'h79;
          bsel = 1'h1;
          M_game_fsm_d = START_game_fsm;
        end
      endcase
    end
  end
  
  always @(posedge clk) begin
    M_game_fsm_q <= M_game_fsm_d;
  end
  
endmodule
